doublet:
  dx/x0 : 0.0525
  eps: 0.0015

triplet:
  angle diff x: 0.001
  angle diff y: 0.001

binning:
  num bins x: 1000

qubo parameters:
  b_ij conflict: 1.0
  b_ij match: two norm angle standard deviation
  a_i: two norm angle standard deviation

scale range parameters:
  z_scores: True
  quality: [-0.2, 0.2]
  interaction: [-1.0, -0.8]