doublet:
  dx/x0 : 0.053
  eps: 0.0015

triplet:
  angle diff x: 0.001
  angle diff y: 0.001

binning:
  num bins x: 1000

qubo parameters:
  b_ij conflict: 1.0
  b_ij match: -1.0
  a_i: 0.0

scale range parameters:
  z_scores: False
  quality: null
  interaction: null